-- MySQL Script generated by MySQL Workbench
-- Sat Feb 18 23:31:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`osobowe`
-- -----------------------------------------------------
CREATE TABLE `osobowe` (
  `idosobowe` INT NOT NULL AUTO_INCREMENT,
  `marka` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `rocznik` INT NULL,
  `miejsca` INT NULL,
  `paliwo` VARCHAR(45) NULL,
  `konie` INT NULL,
  `cena` VARCHAR(45) NULL,
  `typ` VARCHAR(45) NULL,
  `zdjecie1` VARCHAR(45) NULL,
  `zdjecie2` VARCHAR(45) NULL,
  PRIMARY KEY (`idosobowe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ciezarowe`
-- -----------------------------------------------------
CREATE TABLE `ciezarowe` (
  `idciezarowe` INT NOT NULL AUTO_INCREMENT,
  `marka` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `rocznik` INT NULL,
  `konie` INT NULL,
  `paliwo` VARCHAR(45) NULL,
  `osie` INT NULL,
  `typ` VARCHAR(45) NULL,
  `zdjecie` VARCHAR(45) NULL,
  PRIMARY KEY (`idciezarowe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news`
-- -----------------------------------------------------
CREATE TABLE `news` (
  `idnews` INT NOT NULL AUTO_INCREMENT,
  `tytul` VARCHAR(45) NULL,
  `podtytul` VARCHAR(45) NULL,
  `text` TEXT(400) NULL,
  PRIMARY KEY (`idnews`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
